### PR TITLE
quantum.bst v0.1

### PR DESCRIPTION
**Pull request by dwierichs**
Here you go :) 
A first version covering articles, repositories and websites.
There are plenty of other reference classes that are covered by default, but because I am not used to those citation types, I would need input on how to format them (for now they are standard, but most likely not consistent with article and the new ones).

In order to check out the behaviour, have a look at quantum_bst_demo.pdf, where I tried to cover "each possible" scenario.

Let me know what you think! :-)

### CODE REVIEW

**Comment by johannesjmeyer** [comment]
Some things I noted:
- I added a reference from the arxiv via Zotero that does not have the `year` but a specified `date` field, from which we should extract the year. 
- I also added a reference (`holevo2012quantum`) that has `journaltitle` specified instead of `journal`, but it is not used (apparently the modern approach is to have `journaltitle` and maybe `shortjournal` instead of simply `journal`).
- Apparently, citations are not grouped, so you get [3,4,5,6,7] instead of [3-7] (I would be for sort&compress by default, I don't know if that is something that can be done in the bst file)
- Maybe we should rethink the italics for the article title. In the actual font of the quantumarticle document class it doesn't look that good. Maybe try enclosing it in quotes instead?
- Currently, volume numbers (aka Journal 75(4) instead of Journal 75) are displayed, I don't think we need them

**Comment by dwierichs** [comment]
Perfect, thanks for the feedback, I'll work on it from here!
Good catches regarding the journaltitle, grouping and date.
I will make some easy to switch options for the title formatting such that we reconsider later, for now I'll go with your idea of using quotes.

**Comment by cgogolin** [comment]
Thanks! Looks like this is going in the right direction.

I am undecided about sort and compress. It is arguably much nicer to read, but then it makes it harder to find all places in a paper where a certain reference is cited by searching the pdf.

Now sure what you think is more important. Just want to make sure we make an informed decision.

On May 14, 2021 4:30:18 PM GMT+02:00, Johannes Jakob Meyer ***@***.***> wrote:
>Some things I noted:
>- I added a reference from the arxiv via Zotero that does not have the `year` but a specified `date` field, from which we should extract the year. 
>- I also added a reference (`holevo2012quantum`) that has `journaltitle` specified instead of `journal`, but it is not used (apparently the modern approach is to have `journaltitle` and maybe `shortjournal` instead of simply `journal`).
>- Apparently, citations are not grouped, so you get [3,4,5,6,7] instead of [3-7] (I would be for sort&compress by default, I don't know if that is something that can be done in the bst file)
>- Maybe we should rethink the italics for the article title. In the actual font of the quantumarticle document class it doesn't look that good. Maybe try enclosing it in quotes instead?
>- Currently, volume numbers (aka Journal 75(4) instead of Journal 75) are displayed, I don't think we need them
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/quantum-journal/quantum-journal/pull/123#issuecomment-841280368
-- 
Christian Gogolin
http://www.cgogolin.de

**Comment by cgogolin** [comment]
Another source of bib entries that we can use for tests is https://www.doi2bib.org/ and of course Quantum's own bib data should display well.

BTW: If you have any constructive criticism about the bib data we display on the papers' pages, let me know.

On May 14, 2021 4:50:15 PM GMT+02:00, David Wierichs ***@***.***> wrote:
>Perfect, thanks for the feedback, I'll work on it from here!
>Good catches regarding the journaltitle, grouping and date.
>I will make some easy to switch options for the title formatting such that we reconsider later, for now I'll go with your idea of using quotes.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/quantum-journal/quantum-journal/pull/123#issuecomment-841291915
-- 
Christian Gogolin
http://www.cgogolin.de

**Comment by dwierichs** [comment]
I took care of all the mentioned things, will take a look at how Quantum's bib entries are displayed by default and whether one could improve them.
Here are some new questions that popped up:
1. arxiv references should be `article`s not `misc`s, in my opinion, however, the example from the arxiv directly uses the latter.
2. Order of preference for the journal title? I'd suggest `journal` before `shortjournal` before `journaltitle`.
3. Do we want to print out `note`s? The one produced by the  web of science, for example, seems quite inadequate.
4. The standard bst files turn titles to all lower case, making the braces in `title={A title with a {C}apitalized word}` necessary. Pros: The titles are formatted uniformly and this is the standard in other .bst files. Cons: If the bibliography entries do not include braces around letters to be capitalized, they will be turned to lower case. I have seen this going wrong in papers, the references from arxiv and zotero are examples. I think leaving capitalization to the authors of the cited work is a more modern approach, maybe.
5. If we use quotes for the title, which ones do we want? Require the `csquotes` package and use `\enquote` or default ` ``example''`?

**Comment by dwierichs** [comment]
Sorting and compressing is a matter of the latex preamble, at least that seems to be the easiest solution:
```latex
\usepackage[numbers, sort&compress]{natbib}
```
will do the job.
This also means, it is easy to change for authors. We could not sort and compress by default and if there are cases of many entries, making the citation unreadable, authors may activate it (for example for 3 entries, I'd find [34,35,36] still okay).

**Comment by johannesjmeyer** [comment]
> 1. arxiv references should be `article`s not `misc`s, in my opinion, however, the example from the arxiv directly uses the latter.

I agree, but as the arxiv outputs `misc` we should still make that look as much like the other arxiv references I would say.

> 2. Order of preference for the journal title? I'd suggest `journal` before `shortjournal` before `journaltitle`.

That is a quite important question that we didn't explicitly settle yet. Do we want to use abbreviated journal names? I would say no, because space is free for us, but this is not a strong opinion. The argument for short journal names (information densities, everybody knows them) is also good. Nicolai Friis had a strong opinion for short journal names.

> 3. Do we want to print out `note`s? The one produced by the  web of science, for example, seems quite inadequate.

Yeah, I would not. Only if it is the only field maybe?

> 4. The standard bst files turn titles to all lower case, making the braces in `title={A title with a {C}apitalized word}` necessary. Pros: The titles are formatted uniformly and this is the standard in other .bst files. Cons: If the bibliography entries do not include braces around letters to be capitalized, they will be turned to lower case. I have seen this going wrong in papers, the references from arxiv and zotero are examples. I think leaving capitalization to the authors of the cited work is a more modern approach, maybe.

Good point, I think the fact that you have to use braces to save capitalization is a pretty standard behaviour by now. I think I can even update the Zotero export (it's just javascript) to do these things.

> 5. If we use quotes for the title, which ones do we want? Require the `csquotes` package and use `\enquote` or default ``  ``example'' ``?

I would go for the latter. `\enquote` will change if somebody changes the language of the text, but that is not a usecase that we should cover in my opinion. It is therefore better to not add another dependency.

And thanks for the hint about sort and compress!

@cgogolin I looked at the BibTeX data for quantum and it looks fine. Maybe, as we introduced the non-standard `code` tag for code associated with submission, it would be nice to give the authors the possibility to add that so that it also shows up in the bibtex entry. Btw, is the BibTeX obtained from CrossRef generated by CrossRef or by you?

**Comment by cgogolin** [comment]
I agree with all points, especially not adding another dependency.

On the abbreviation: How does that work? Via some lookup table? What happens if a new journal is created? What if authors themselves already put abbreviated journal titles in their .bib? What if they do this only for some entries?

We generate the bibtex ourselves from our own meta data as the results returned by Crossref were not satisfactory.

On the code tag: can you please open an issue against O-3PO? I will then look into this in an upcoming release. Thanks! 

On May 18, 2021 10:51:35 AM GMT+02:00, Johannes Jakob Meyer ***@***.***> wrote:
>> 1. arxiv references should be `article`s not `misc`s, in my opinion, however, the example from the arxiv directly uses the latter.
>
>I agree, but as the arxiv outputs `misc` we should still make that look as much like the other arxiv references I would say.
>
>> 2. Order of preference for the journal title? I'd suggest `journal` before `shortjournal` before `journaltitle`.
>
>That is a quite important question that we didn't explicitly settle yet. Do we want to use abbreviated journal names? I would say no, because space is free for us, but this is not a strong opinion. The argument for short journal names (information densities, everybody knows them) is also good. Nicolai Friis had a strong opinion for short journal names.
>
>> 3. Do we want to print out `note`s? The one produced by the  web of science, for example, seems quite inadequate.
>
>Yeah, I would not. Only if it is the only field maybe?
>
>> 4. The standard bst files turn titles to all lower case, making the braces in `title={A title with a {C}apitalized word}` necessary. Pros: The titles are formatted uniformly and this is the standard in other .bst files. Cons: If the bibliography entries do not include braces around letters to be capitalized, they will be turned to lower case. I have seen this going wrong in papers, the references from arxiv and zotero are examples. I think leaving capitalization to the authors of the cited work is a more modern approach, maybe.
>
>Good point, I think the fact that you have to use braces to save capitalization is a pretty standard behaviour by now. I think I can even update the Zotero export (it's just javascript) to do these things.
>
>> 5. If we use quotes for the title, which ones do we want? Require the `csquotes` package and use `\enquote` or default ``  ``example'' ``?
>
>I would go for the latter. `\enquote` will change if somebody changes the language of the text, but that is not a usecase that we should cover in my opinion. It is therefore better to not add another dependency.
>
>And thanks for the hint about sort and compress!
>
***@***.*** I looked at the BibTeX data for quantum and it looks fine. Maybe, as we introduced the non-standard `code` tag for code associated with submission, it would be nice to give the authors the possibility to add that so that it also shows up in the bibtex entry. Btw, is the BibTeX obtained from CrossRef generated by CrossRef or by you?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/quantum-journal/quantum-journal/pull/123#issuecomment-842984711
-- 
Christian Gogolin
http://www.cgogolin.de

**Comment by johannesjmeyer** [comment]
There is an ISO standard for abbreviation that everybody is following, so if a new journal pops up there is a standardized way to abbreviate it. But the abbreviations have to be present in the BibTeX as far as I know. In a perfect world, BibTeX entries would have both `journaltitle` and `shortjournal` set to the appropriate values and the bibstyle can choose which one it would display. I guess it would then make sense for us to do `journal` > `shortjournal` > `journaltitle` as per Davids suggestion (or the last two swapped if we prefer long titles). In this case `journal` would be like the authors wants to display it and he can fill it as he sees fit.

Okay, so CrossRef creates its BibTeX from the metadata. I guess then you should somehow put the code tag in there, but I will elaborate in the O-3PO issue.

**Comment by dwierichs** [comment]
> I agree, but as the arxiv outputs misc we should still make that look as much like the other arxiv references I would say.

I see mostly three options for this:
1. Require authors to change `misc` to `article` 
2. Make the `misc` entry compile like `article` conditioned on "arXiv" being in some field/some certain tags being provided.
3. Make the `misc` entry compile like `article`. This kind of defeats the purpose of having a separate class and just keeps it for the arXiv's output sake.
I personally would favour option 2 regarding the behaviour, but it will be more complicated than 1 and 3. For now I implemented the condition `archivePrefix=="arXiv" and primaryClass!=None` (using Python syntax for sanity).

> Do we want to use abbreviated journal names? I would say no, because space is free for us, but this is not a strong opinion. The argument for short journal names (information densities, everybody knows them) is also good. Nicolai Friis had a strong opinion for short journal names.

It sounds more "open" in my ears not to use abbreviated journal names. Even if there is an ISO standard for the abbreviations (which btw. are hardcoded in `.bst` files as Johannes says and have to be updated manually or downloaded somewhere), I don't really see the benefit, just more work in particular to keep `quantum.bst` up to date. But we could ask Nicolai Friis about that? 

> Yeah, I would not. Only if it is the only field maybe?

Sounds good! I will implement this in the `misc` class but not print `note` in any other case (Other reference classes have certain fields required, so the '`note`-only' case can't really pop up there.

>Good point, I think the fact that you have to use braces to save capitalization is a pretty standard behaviour by now. 

Alright, will keep it then :)

> I would go for the latter. \enquote will change if somebody changes the language of the text, 

Done.

**Comment by dwierichs** [comment]
Regarding the arXiv via Zotero: Zotero puts the arxiv information into the journal field and mimics a proper published entry. I'd assume that this is something to be set up in Zotero and not to handle this separately in the `.bst`, right?

There also seem to be tags generated by Zotero that are not recognized by default `.bst` files like `eprinttype`. Do we want to do anything about this or just ignore them (which is what bibtex does by default).

**Comment by cgogolin** [comment]
Trying to require authors to change misc to article will not work.

2 would be the best solution, I think, unless it is so complicated that it will likely break in the future.

I wouldn't mind if misc looked like article (depending on which fields are set). What is the use of misc anyway?


On May 22, 2021 9:27:08 AM GMT+02:00, David Wierichs ***@***.***> wrote:
>> I agree, but as the arxiv outputs misc we should still make that look as much like the other arxiv references I would say.
>
>I see mostly three options for this:
>1. Require authors to change `misc` to `article` 
>2. Make the `misc` entry compile like `article` conditioned on "arXiv" being in some field/some certain tags being provided.
>3. Make the `misc` entry compile like `article`. This kind of defeats the purpose of having a separate class and just keeps it for the arXiv's output sake.
>I personally would favour option 2 regarding the behaviour, but it will be more complicated than 1 and 3.
>
>> Do we want to use abbreviated journal names? I would say no, because space is free for us, but this is not a strong opinion. The argument for short journal names (information densities, everybody knows them) is also good. Nicolai Friis had a strong opinion for short journal names.
>
>It sounds more "open" in my ears not to use abbreviated journal names. Even if there is an ISO standard for the abbreviations (which btw. are hardcoded in `.bst` files as Johannes says and have to be updated manually or downloaded somewhere), I don't really see the benefit, just more work in particular to keep `quantum.bst` up to date. But we could ask Nicolai Friis about that? 
>
>> Yeah, I would not. Only if it is the only field maybe?
>
>Sounds good! I will implement this in the `misc` class but not print `note` in any other case (Other reference classes have certain fields required, so the '`note`-only' case can't really pop up there.
>
>>Good point, I think the fact that you have to use braces to save capitalization is a pretty standard behaviour by now. 
>
>Alright, will keep it then :)
>
>> I would go for the latter. \enquote will change if somebody changes the language of the text, 
>
>Done.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/quantum-journal/quantum-journal/pull/123#issuecomment-846368289
-- 
Christian Gogolin
http://www.cgogolin.de

**Comment by cgogolin** [comment]
Oh dear...

We should try to be as forgiving as possible. But if zotero does something that is impossible to accommodate then so be it.

On May 22, 2021 9:42:01 AM GMT+02:00, David Wierichs ***@***.***> wrote:
>Regarding the arXiv via Zotero: Zotero puts the arxiv information into the journal field and mimics a proper published entry. I'd assume that this is something to be set up in Zotero and not to handle this separately in the `.bst`, right?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/quantum-journal/quantum-journal/pull/123#issuecomment-846369717
-- 
Christian Gogolin
http://www.cgogolin.de

**Comment by dwierichs** [comment]
> 2 would be the best solution, I think, unless it is so complicated that it will likely break in the future.

Yeah, let's go with this one for now. If arxiv changes the way they provide the own references, we can adapt easily.
And that should be the only source of `misc`s that we want to be `article`s.

> I wouldn't mind if misc looked like article (depending on which fields are set). What is the use of misc anyway?

It can be used for anything, in particular infamous references in the form of "private correspondence" or such things...
I think it is important not to break support for this for legacy reasons, and therefore keep it as a reference class that essentially just puts out whatever you give to its standard fields, including a `note`.

> We should try to be as forgiving as possible. But if zotero does something that is impossible to accommodate then so be it.

My fear here would be a huge dependency tree to all major bibliography tools. @johannesjmeyer, do you know whether there is the option to just reproduce the `misc` entry of arxiv articles via Zotero?

**Comment by johannesjmeyer** [comment]
I think we need not be super concerned about the `misc` entries, I just added them so we see how they render. It should just not look totally awkward, but we need not try to fix everything that people _might_ come up with. In the end people are responsible for making their bibliography work and not we. So I would say if option 2 is not too hard to implement we do that, otherwise people just have to look after their bibliography more carefully.

Considering the journal names I actually assumed that you always have to give the short journal explicitly, I didn't know that was sometimes handled by the bibstyle. So then `journal > journaltitle > shortjournal`? 

Can you add options to bibstyles? So that maybe we can add the option to prefer `shortjournal`?

**Comment by johannesjmeyer** [comment]
Ah, by the way -- one type we should also check is `inproceedings` for stuff that was published, e.g. in NeurIPS.

**Comment by johannesjmeyer** [comment]
@dwierichs I added two test cases from my Zotero to that end

**Comment by dwierichs** [comment]
Yeah, the mainreason the `misc`s play a role is because arxiv chose to put its articles in that format :D

>Ah, by the way -- one type we should also check is inproceedings for stuff that was published, e.g. in NeurIPS.

Yeah I am working my way through, by relevance :D I will proceed (haha) with those entries like for book/inbook: Make them basically redundant, because they differ only by tiny extra information for the "in" versions.

Thanks for the test cases! Happy for all of them you throw at it :)

**Comment by dwierichs** [comment]
Oh, and when exporting an arxiv reference via Zotero, is there the option to not have it produce a journal-like article but just the original?

**Comment by johannesjmeyer** [comment]
Sounds good :)

And re Zotero/arXiv: I have no clue. I just use the Zotero plugin without altering anything, which is probably also what the other possible users would do.

**Comment by cgogolin** [comment]
It would be great if you could these the bib style with the bibliographies of some of the recently published papers in Quantum. Making that a proper unit test is probably impossible as the output must be looked at by a human but it would be a good way to see which strange things authors actually commonly do. We used this approach of "learning what the community does" when writing and refining the latex parser on O-3PO.


On May 22, 2021 5:31:46 PM GMT+02:00, Johannes Jakob Meyer ***@***.***> wrote:
>Sounds good :)
>
>And re Zotero/arXiv: I have no clue. I just use the Zotero plugin without altering anything, which is probably also what the other possible users would do.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/quantum-journal/quantum-journal/pull/123#issuecomment-846424262
-- 
Christian Gogolin
http://www.cgogolin.de

**Comment by johannesjmeyer** [comment]
That is a good idea, but wouldn't we need the bib-files for that? On the Arxiv you usually only have the (already formatted) bbl files, right?

I also recently wrote a paper in quantum style, I can try it out with that. But maybe we can inquire some people if they can send the bibfile.

**Comment by cgogolin** [comment]
I agree that it is a reasonable assumption that people will use e.g. Zotero with default settings, expect things to work, and will not necessarily know (or want to learn) how to fix things in Zotero.

One other general piece of advice: People generally do not read documentation and ignore LaTeX warnings (almost nobody looks at them) but they (are forced to) take into account errors that make the compilation fail. Such errors, if they come with clear instructions for how to fix things, can be a powerful way of "documenting" latex code.

It is much nicer to tell a user that their bib could not be reasonably formatted and tell them what to changed, instead of silently outputting garbage.

On May 22, 2021 5:31:46 PM GMT+02:00, Johannes Jakob Meyer ***@***.***> wrote:
>Sounds good :)
>
>And re Zotero/arXiv: I have no clue. I just use the Zotero plugin without altering anything, which is probably also what the other possible users would do.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/quantum-journal/quantum-journal/pull/123#issuecomment-846424262
-- 
Christian Gogolin
http://www.cgogolin.de

**Comment by dwierichs** [comment]
> One other general piece of advice: People generally do not read documentation and ignore LaTeX warnings (almost nobody looks at them) but they (are forced to) take into account errors that make the compilation fail. Such errors, if they come with clear instructions for how to fix things, can be a powerful way of "documenting" latex code.

I agree that latex warnings are usually ignored by users. However, bibtex specific errors like a missing field are actually well-documented in the warnings. Changing the warning behaviour in these cases to actually crashing the compiling is quite a major change (One might want to add references add some point and take care of their completeness & formatting later on, for example). However, it could be a nice way to avoid [?] floating around, which were overlooked.
Also I think one would want to collect all warnings before raising an error, so that one does not have to recompile error by error. Does that make sense? 
So should we change the basic behaviour of bibtex when encountering problematic entries? (Note that we can't do much about other problems like special characters, wrong punctuation in the `.bib` file and similar issues, because those are caught by latex)

**Comment by dwierichs** [comment]
Having some `.bib` files available would be a massive help to account for corner cases etc.!

**Comment by cgogolin** [comment]
I don't know what is possible with bibtex and also not what is feasible and how much effort you can dedicate, so no pressure.

Catching [?] would be great!

Probably bibtex can also inject code in the bbl that then leads to an error during the LaTeX pass.


On May 23, 2021 3:38:35 PM GMT+02:00, David Wierichs ***@***.***> wrote:
>> One other general piece of advice: People generally do not read documentation and ignore LaTeX warnings (almost nobody looks at them) but they (are forced to) take into account errors that make the compilation fail. Such errors, if they come with clear instructions for how to fix things, can be a powerful way of "documenting" latex code.
>
>I agree that latex warnings are usually ignored by users. However, bibtex specific errors like a missing field are actually well-documented in the warnings. Changing the warning behaviour in these cases to actually crashing the compiling is quite a major change (One might want to add references add some point and take care of their completeness & formatting later on, for example). However, it could be a nice way to avoid [?] floating around, which were overlooked.
>Also I think one would want to collect all warnings before raising an error, so that one does not have to recompile error by error. Does that make sense? 
>So should we change the basic behaviour of bibtex when encountering problematic entries? (Note that we can't do much about other problems like special characters, wrong punctuation in the `.bib` file and similar issues, because those are caught by latex)
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/quantum-journal/quantum-journal/pull/123#issuecomment-846564816
-- 
Christian Gogolin
http://www.cgogolin.de

**Comment by dwierichs** [comment]
Yes, exactly, that is how I would do it. As far as I can see, there is no error command in bibtex, so I'd try to cache all warnings that arise and then write a line to the `.bbl` that makes latex crash. This would be the way of "catching" [?], i.e. they simply don't occur because latex is interrupted :-)

**Comment by johannesjmeyer** [comment]
I just tried to compile my paper with the bibstyle and it looks nice :) I also changed the bbl manually to see how it would look like with italics:
[paper_quotationmarks.pdf](https://github.com/quantum-journal/quantum-journal/files/6560236/paper_quotationmarks.pdf)
[paper_italics.pdf](https://github.com/quantum-journal/quantum-journal/files/6560238/paper_italics.pdf)

I would consider (because eprint is also) to write `doi:` as lower case.

**Comment by dwierichs** [comment]
Sorry for the silence... Which title formatting do you prefer? I think I actually find italics visually more clear.

**Comment by cgogolin** [comment]
I don't have a strong opinion. Maybe slightly leaning towards quotation marks as they are preserved when converting to plain text.


On June 13, 2021 1:47:39 PM GMT+02:00, David Wierichs ***@***.***> wrote:
>Sorry for the silence... Which title formatting do you prefer? I think I actually find italics visually more clear.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/quantum-journal/quantum-journal/pull/123#issuecomment-860197781
-- 
Christian Gogolin
http://www.cgogolin.de

**Comment by johannesjmeyer** [comment]
We could prepare two sample documents and show them around so we can get some feedback from the end users. That will be a slow process but these people have to use it in the end. I think I would be able to collect some good feedback in our group as soon as I have an example document

PS: Actually I already made those documents, so I will just send them around and see what people think!

**Comment by dwierichs** [comment]
Alright, very cool! Note that the bibstyle is still WIP. For example a `book` reference containing volume, chapter and pages will be ill-formated. But having feedback on the general decisions we made and on the new reference types `repository` and `website` would be amazing! I'm sorry this PR is going so slow, unfortunately I'm quite swamped currently.

**Comment by johannesjmeyer** [comment]
Don't worry, the pace is fine :) So far, people are _very much_ in favor of italics, so I would say we go with that! I'll also send them the PDF that displays the new reference types to get some feedback on them.

PS: Actually, @dwierichs, could you update the title formatting to italics and then notify me? Then I'll send the quantum_bst_demo.pdf around in the group

**Comment by johannesjmeyer** [comment]
Some input from Philippe Faist: 
> Here are my own personal preferences: too much italics, like too much quotes, removes the visual emphasis that italics give. Quotation marks look pretty heavy, too. I prefer a simple period to separate authors and title. (Author A and Author B. Some title goes here. Physical Review bla bla bla.) Then I'm not a fan of spelling out links or doi's. I prefer if they are directly encoded in a hyperlink. Spelled out, they are only useful if printed on paper, but is anyone really going to copy the doi instead of copying the reference information?
I still think the italics are nice though.

**Comment by johannesjmeyer** [comment]
@cgogolin is there a hard requirement that we output the DOI in the bibliography from CrossRef? Most people I talked to would prefer not to see the DOI and just to have it when clicking the link to the paper.

**Comment by cgogolin** [comment]
Yes, to my understanding having the DOI link URL visible is a hard requirement.

On June 16, 2021 11:56:25 AM GMT+02:00, Johannes Jakob Meyer ***@***.***> wrote:
***@***.*** is there a hard requirement that we output the DOI in the bibliography from CrossRef? Most people I talked to would prefer not to see the DOI and just to have it when clicking the link to the paper.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/quantum-journal/quantum-journal/pull/123#issuecomment-862222244
-- 
Christian Gogolin
http://www.cgogolin.de

**Comment by ADB991** [comment]
I don't think the DOI link URL must be visible, as per the explicit example at page 2 of [the template](https://github.com/quantum-journal/quantum-journal/blob/master/quantum-template.pdf).

I think having the Journal details be hyperlinked to the DOI url would remove a lot of spacing issues, especially in doublecolumn format.

I would have loved to have this available while typesetting y article of Quantum. Keep up the good work!

**Comment by ADB991** [comment]
Actually, I cloned the directory and tried it out. I love it! I found quite a big issue though. Both in `article` and `misc` classes, the presence of the `archivePrefix` field messes up the bibliographic entry, so that only author, title, doi and arxiv link are printed (no journal, volume or year). Try it for example on this, with and without the `archivePrefix' field.
```
@article{hoehn2017toolbox,
  title = {Toolbox for Reconstructing Quantum Theory from Rules on Information Acquisition},
  author = {H\"{o}hn, Philipp A.},
  year = {2017},
  month = dec,
  volume = {1},
  pages = {38},
  doi = {10.22331/q-2017-12-14-38},
  archivePrefix = {arXiv},
  eprint = {1412.8323},
  eprinttype = {arxiv},
  journal = {Quantum}
}
```
The same happens for `misc` classes (no year is printed), and indeed it happened on the first misc reference in the [quantum_bst_demo.pdf](https://github.com/dwierichs/quantum-journal/blob/quantum_bibstyle/quantum_bst_demo.pdf) (top of page 3).

While it's pretty easy to fix on the user side (just go and delete all `archivePrefix` fields) it is also soulcrushing. I have no clue on how all the code works, but I hope it's not too difficult to fix on your side.


Note that the bib entry above was generated automatically by my Zotero with betterbibtex. Perhaps I have a different configuration than yours, but I will definitely not be the only person having this problem. Additionally, the `archivePrefix`, `eprint` and `eprinttype' fields are generated automatically by the arXiv API when you click on "Export Bibtex Citation" on any preprint that does not correspond to a published article (try it on [this](https://arxiv.org/abs/2107.11497) for example).

**Comment by dwierichs** [comment]
Thank you @ADB991 for the DOI update and the bug report! :+1: 
I'll wait for a response from @johannesjmeyer and/or @cgogolin regarding the former, if that is okay, and take care of the latter :)
I'm hoping to be able to put some more time in soon!

**Comment by johannesjmeyer** [comment]
Thank you so much for your input @ADB991! I think the bug should be relatively straightforward to fix.

And re dois: if they need not be displayed then I would go for hyperlinking the journal/issue/page part of the citation. I think this happens somehow already under some combination of doi and hyperref packages and there it is quite nice.
________________________________

**Comment by ADB991** [comment]
Glad you found that useful!

revtex4-1 does the DOI hyperlinking on the journal/volume/issue part and I think it’s pretty neat.

Btw
This is what the acceptance email I got says about DOI:

All citations to works that have a DOI must contain clickable hyperlinks to the URL associated with the work's DOI. These links must start with https://doi.org/(prefered) or http://dx.org/; links to the website of the publisher are not sufficient.

**Comment by ADB991** [comment]
I don’t know how much of a hassle would be to do it, but you could provide a minimal set of options for the .bst file, allowing the user to choose about the DOI (a bit like revtex allows to set `longbibliography` in the options of documentclass) or perhaps provide two different .bst files.

**Comment by dwierichs** [comment]
Hi @johannesjmeyer , @ADB991 , @cgogolin .
I finally had time to implement all discussed changes, make them consistent across reference classes and continue the template discussing the classes.
News:
1. The doi reference is put behind Journal/Volume/Number where applicable, and behind corresponding tags for other classes like `book`. This can be deactivated by adding
```
@preamble{"\MakeDoiLinksExplicit"}
```
to the `.bib` file.
2. The `.bst` file now tries to catch warnings that are within its domain; unfortunately, this does not cover all (but some) syntax errors but it covers missing field warnings. Caught warnings will trigger a compilation error as well as a (red) entry in the compiled bibliography. This behaviour can be deactivated by adding
```
@preamble{"\DoNotMakeWarningsErrors"}
```
to the `.bib` file.
3. The class `repository` now has a `version` tag as well as a `commit` tag that can be used to mark that the provided link is a specific commit. This replaces a potential "access date" comment that otherwise might be needed. No processing happens there, though, such that linking to commit `abcdefg` while printing `commit:1234567` is possible and the user has to take care of this being correct (this should not be an issue, because such citations should be few and manually created, I think).
4. the `website` class now has an `urldate` field like in some other bibstyles. It prints as `(accessed: <urldate>)`.
5. Explanations of the optional settings above (warnings --> errors and implicit DOI links) as well as the error-catching mechanism were added to the demo latex document.
6. I removed the "eprint:" printing, as "eprint: arXiv:1234.56789" looks strange and "eprint" barely adds information.

I would ask you to take a look at the document and to check whether there are flaws/design choices we should change :)
The tests seem to "pass" as far as I can tell, I'd be happy about more test cases :)
I asked a few people for their personal preferences and I mostly got very small modification ideas, this might actually meet the taste of many people :D

*Disclaimer:* I put much more effort into the standard classes `article`, `book` and `misc` and other classes might still have bugs, also because there are fewer test cases so far. I'll try to improve in that direction.
Happy for any thoughts you might have!

**Comment by cgogolin** [comment]
This look very very nice! Great work!

Before merging this can you please:

1) update the quantum-template.tex to use this bst
2) update the Readme and add yourself as a contributor
3) add a pdf of the demo to the repository (I know, normally only source files on git but it is good if people can see what they will get without having to download and compile themselves and pdfs are also just text files in the end...)

Shall we also bump the version number of the package as a whole and make a new release, including release to ctan?



On September 22, 2021 9:29:22 PM GMT+02:00, David Wierichs ***@***.***> wrote:
>Hi @johannesjmeyer , @ADB991 , @cgogolin .
>I finally had time to implement all discussed changes, make them consistent across reference classes and continue the template discussing the classes.
>News:
>1. The doi reference is put behind Journal/Volume/Number where applicable, and behind corresponding tags for other classes like `book`. This can be deactivated by adding
>```
***@***.***{"\MakeDoiLinksExplicit"}
>```
>to the `.bib` file.
>2. The `.bst` file now tries to catch warnings that are within its domain; this does unfortunately not cover all (but some) syntax errors and covers missing field warnings. Caught warnings will trigger a compilation error as well as a (red) entry in the compiled bibliography. This behaviour can be deactivated by adding
>```
***@***.***{"\DoNotMakeWarningsErrors"}
>```
>to the `.bib` file.
>3. The class `repository` now has a `version` tag as well as a `commit` tag that can be used to mark that the provided link is a specific commit. This replaces a potential "access date" comment that otherwise might be needed. No processing happens there, though, such that linking to commit `abcdefg` while printing `commit:1234567` is possible and the user has to take care of this being correct (this should not be an issue, because such citations should be few and manually created, I think).
>4. the `website` class now has an `urldate` field like in some other bibstyles. It prints as `(accessed: <urldate>)`.
>5. Explanations of the optional settings above (warnings --> errors and implicit DOI links) as well as the error-catching mechanism were added to the document.
>6. I removed the "eprint:" printing, as "eprint: arXiv:1234.56789" looks strange and "eprint" barely adds information.
>
>I would ask you to take a look at the document and to check whether there are flaws/design choices we should change :)
>The tests seem to "pass" as far as I can tell, I'd be happy about more test cases :)
>I asked a few people for their personal preferences and I mostly got very small modification ideas, this might actually meeting the taste of many people :D
>
>*Disclaimer:* I put much more effort into the standard classes `article`, `book` and `misc` and other classes might still have bugs, also because there are fewer test cases so far. I'll try to improve in that direction.
>Happy for any thoughts you might have!
>
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/quantum-journal/quantum-journal/pull/123#issuecomment-925255010
-- 
Christian Gogolin
http://www.cgogolin.de

**Comment by dwierichs** [comment]
Some open questions:
1. Do we want `quantum.bst` to support a field `shorturl` with which one can specify a shorter, custom URL that is displayed instead of the full URL, in order to allow manual pretty-printing? I found this handy to have in recent draft writing and it would be readily available as a feature :)
2. Is the Quantum bibstyle considered a beta feature?
3. I don't know about the version number, just let me know what I should put in the changelog section of the readme :)
4. I added 2021 to the copyright years, is that correct?
5. Should we be testing the bibstyle a bit more before releasing? This question is kind of tied with whether it is considered beta, I guess...

Took care of the other points :)

**Comment by johannesjmeyer** [comment]
Thank you so much David, that is really really awesome! Concerning your questions:
1. Yes, that would be nice!
2. Yes, we should note that in the text. I am in favour of putting it out there and get real feedback from real people. So therefore we just should put that people should open a Git issue or write an email to latex@quantum-journal.org if they encounter problems.

Some other remarks: 
- In the bst demo, you write that titles will be printed in italics, but when I look at the PDF in the repo it is in regular serif font.
- I would remove the test cases from the final document as people will use this as a reference

After merging this, we can release the new version which also includes the update to quantum-plots! This will be very nice and I will take care of the pushing to CTAN.

**Comment by dwierichs** [comment]
Took care of everything but the titles comment: Did we in the end decide for quotation marks? I kind of forgot and am not entirely sure, after rereading the PR history :D

_edit:_ The title formatting is taken care of.

**Comment by cgogolin** [comment]
I like quotation marks because they survive conversion to plain text and thus make automated processing a little easier, but no strong opinion.

On October 9, 2021 2:24:38 PM GMT+02:00, David Wierichs ***@***.***> wrote:
>Took care of everything but the titles comment: Did we in the end decide for quotation marks? I kind of forgot and am not entirely sure, after rereading the PR history :D
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/quantum-journal/quantum-journal/pull/123#issuecomment-939288743
-- 
Christian Gogolin
http://www.cgogolin.de

**Pull request merged**
