### PR TITLE
WIP: Template and example for use with Pandoc

### PR DESCRIPTION
**Pull request by cgranade**
Following #13, this PR similarly provides a template and example for producing `{quantumarticle}`-formatted articles with Pandoc. This allows for very minimal Markdown syntax to be used in preparing articles, and for simplified metadata syntax (in particular, Pandoc uses YAML headers, as seen in `examples/pandoc-example.md`).

Still missing is an installer for the new template; I'm not sure if it makes more sense to include this in the new `install.sh` and `install.ps1` scripts merged with #12, or to make a separate installer.

### CODE REVIEW

**Comment by cgogolin** [comment]
Just to keep you up to date on changes in quantum-template.tex: the way \hyperref is recommended to be included has changed and in the end of the first paragraph after the abstract a sentence has been added describing the new "click the title" feature of the class.

**Comment by cgranade** [comment]
Keeping the Pandoc example in sync with the plain-LaTeX example is a bit harder than the case of the LyX example in #13, as there's a number of LaTeX features that aren't supported by Pandoc (in this case, the most notable being `\begin{theorem}`). This is rather by intention, since Pandoc focuses on the typesetting features in common between several different markup languages. I think it's still useful to have a Pandoc template in place, but that does at the least mandate that the example for Pandoc look a bit different than the other two examples.

**Comment by cgogolin** [comment]
Is it then really worth developing the pandoc template? I mean, how many people are going to be using it if it can not even do theorems? How does Pandoc work in practice? Do authors in the end export to LaTeX and then have that code typeset regularly by LaTeX on the arXiv?

**Comment by cgranade** [comment]
At least personally, I make rather extensive use of Pandoc, in part because it's a simple enough format that I find it much nicer to collaborate on when I can. From that perspective, I think that offering a Pandoc template provides users a nice resource and helps make `{quantumarticle}` more accessible. As for posting to arXiv, Pandoc can generate LaTeX, which can then be uploaded as normal.

**Comment by cgogolin** [comment]
Ok, good, thanks for clarifying.

Shall I merge this pull request into develop so that it gets included into the next release, which I will probably do next week?

**Comment by cgranade** [comment]
If it's alright, I'd like to improve the example a little more first, and to get `install.sh` working as well as `install.ps1`. (Maintaining two installers is a pain, but I don't know of a better solution, as long as Windows defaults to PowerShell and everyone else to bash.)

**Comment by cgogolin** [comment]
That's good. Take as much time as you want.

**Comment by cgogolin** [comment]
Ah, one more thing: We should think about the directory structure. People not familiar with Lyx and Pandoc might get confused if there are many files in the base directory. Maybe it would be better to put all Lyx related stuff in a lyx direcory and all Pandoc related stuff in a pandoc directory? I think it would be good if people only wanting to use plain vanilla LaTeX can directly find the .cls in the main directory.

In the Readme we can then explain the different install mechanisms (manual for just plain LaTeX, manual for Lyx, manual for Pandoc and install.sh, install.psh). Do you agree?

**Comment by cgranade** [comment]
I think that makes a lot of sense, yeah. I wasn't sure how to structure things with the initial WIP PRs, so I'll readily admit it's not really that optimal at the moment. To be concrete, my current approach was to use `layouts/`_`<name>`_ to hold layouts for _`<name>`_, but this has the unfortunate side effect of leaving lots of seemingly extraneous junk in `examples/`.

**Comment by cgogolin** [comment]
Closing this because of a lack of activity.

**Pull request closed without merging**
