### PR TITLE
Prevent hyphenation of author names

### PR DESCRIPTION
**Pull request by cgogolin**

### CODE REVIEW

**Review by johannesjmeyer — APPROVED** [review]
Looks good, tested it and found no adverse effects.

**Comment by cgogolin** [comment]
Maybe it would be even better to use a \mbox to make sure the whole name ends up on one line? Not sure if LaTeX can be told to never leave an mbox hang over the right margin though...

**Comment by cgogolin** [comment]
The best is probably flushleft in combination with mbox but we should carefully test this.

We probably should also use flushleft for the affiliations?

**Comment by johannesjmeyer** [comment]
What will be changed by introducing `flushleft`? And won't we get a problem then with the titlepage where the authornames should be centered?

And I'm pro `mbox`, I've already seen it a couple of times in RevTeX papers that people do it via `\author{\mbox{John Doe}}`.

**Comment by johannesjmeyer** [comment]
Okay, I just realized what `flushleft` changes. See my commit for my take on this: I added a `flushleft` conditional on `@titlepage` and an `mbox` around the author name. I didn't include a `flushleft` for the affiliations because they already render correctly from my point of view.

**Comment by cgogolin** [comment]
I have removed the \hyphenpenalty as this now seems no longer necessary.

The affiliations are set as justified in the no titlepage mode. In principle this can also cause problems with overfull hboxes or unfortunate hypenation, but the lines are long enough that this is very unlikely. I think we can leave them as is.

**Pull request merged**
