### PR TITLE
[WIP] Add quantumview documentclass

### PR DESCRIPTION
**Pull request by johannesjmeyer**
Adds the following files:
* `quantumview.cls`: A documentclass derived from `quantumarticle.cls` that provides stripped down functionality that is geared to standardize the process used for typesetting contributions to Quantum Views. It especially only supports one command, namely `html` that converts the output to HTML to ease the publication process.
* `quantumview-template.tex`: An example TeX file that uses the `quantumview` documentclass, and much like `quantumarticle-template.tex` showcases the supported functionalities and dos and don'ts. 
* `quantumview-template.pdf`: The compiled version of the above tex file. 

Todo:
- [x] Strip `quantumview.cls` from all unnecessary `quantumarticle` functionality, only retaining the style
- [x] Add support for HTML rendering through a dedicated option
- [ ] Figure out how to best include standardized bibliography
- [x] Figure out how to output everything in typewriter font if html is set
- [x] Figure out how to replace `\item` with `li` tags (long expand? par arguments?)
- [x] Write template, explain that equations and sections will not be numerated. Redefine \section etc. to not be numbered.
- [x] Add align tags in HTML equations

### CODE REVIEW

**Comment by harrow** [comment]
Is this the right place to discuss a standard (perhaps suggested) bibtex format for Quantum?  I know we give guidance about how to include the DOI links but why not just standardize the rest of the format?  
If we do this, here are some bst files I made which add hyperlinks to the eprint field and otherwise are the same as the ones from arxiv.org.
https://github.com/harrow/arxiv-bibstyle
Those don't have the required DOI links though.

**Comment by johannesjmeyer** [comment]
I think giving people guidance and suggesting a standard format is a very good idea. Quantum intends to leave as much leeway as possible, but many authors just want to have guidelines they can follow (I guess). But this should probably be done in a separate PR / discussed in an issue first.

**Comment by cgogolin** [comment]
I suggested Aram to suggest his styles here after he asked about bibtex styles for Quantum at the same time as us discussing the View template.

I think it would be very good to ship a default style that "simply works" with quantumarticle and the View class.

Maybe we can use one of Aram's styles as a basis and add DOI linking to it?

-- 
Christian Gogolin
http://www.cgogolin.de

**Comment by johannesjmeyer** [comment]
Sure, great idea! I will look into that after I finished the quantumview template.

**Comment by harrow** [comment]
I found this page adds DOI linking.
https://www.math.tamu.edu/~comech/tools/bibtex-doi-eprint/
It says " The hyperlink will be based on the URL field or DOI field or EPRINT field (in this order). "
But is that enough for Quantum?
The DOI is only in the hyperlink target (only if there's no URL field) and won't show up if the paper is printed.  Quantum needs the DOI in the text, not just the link target, right?

**Comment by johannesjmeyer** [comment]
Hi guys, I now have a first version that you should look. Just have a look at `quantumview-template.tex`. To see the corresponding HTML, just add the `html` option for the document class. We have to figure out the following (ping @cgogolin, maybe you can get the people that can answer these on board):
* Is the HTML output as you would expect it to be for uploading to the website?
* What more text should be added to the template?
* Do we want to include figures? I think this is doable, but I would have to know how the embedding code in HTML should look like

I just used the `unsrtnat` style for now because it works out of the box on my system.

**Comment by cgogolin** [comment]
This looks great! I will loop in the others via email in a minute...

I have very few suggestions:
- the equation and align environments need not / should not be converted to $$ as MathJax, and hence our website, supports them fully.
- The included sample .bib file claimed that it was created with the filecontents package and was missing a bibitem. I have pushed a change to address that.
- For me the bibliography style does not produce links to the arXiv version of the cited papers. I am with @harrow that we could make the world a better place if we provided authors with a bibstyle that just works. The apsrev4-1 style does DOI links and arXiv links, but it also produces very short entries...

**Comment by johannesjmeyer** [comment]
> This looks great! I will loop in the others via email in a minute...
> 
> I have very few suggestions:
> 
> * the equation and align environments need not / should not be converted to $$ as MathJax, and hence our website, supports them fully.

Then I will just keep it `\begin{align}...\end{align}` and so on. I just saw on their doc that `\label` and `\ref` also work, nice!

> * The included sample .bib file claimed that it was created with the filecontents package and was missing a bibitem. I have pushed a change to address that.

Thanks!

> * For me the bibliography style does not produce links to the arXiv version of the cited papers. I am with @harrow that we could make the world a better place if we provided authors with a bibstyle that just works. The apsrev4-1 style does DOI links and arXiv links, but it also produces very short entries...

Oh yeah, I didn't take care of the new bib style yet

**Comment by johannesjmeyer** [comment]
@harrow which of your bibstyles do you suggest we use as a basis? What is the difference between plain and abbrv?

**Comment by johannesjmeyer** [comment]
Just to summarize the open questions on this:
* How are images embedded in Wordpress? I need this information to (try to) enable the transformation of `figure` environments. If we don't have this feature it's probably also not super hurtful
* What bibstyle do we use as a basis for the quantum bibstyle? I never used anything besides the standard (phys for biblatex, unsrtnat for natbib) so I don't have an informed opinion on that end. I would appreciate people with an informed opinion to pop in and explain

**Comment by cgogolin** [comment]
I think images are not critical. They Anwar have to be uploaded manually to the wordpress media library and then WP generates the html to embeds them for you. Maybe you can just output an html comment containing the file name so that one knows where which figure it supposed to go.

I have worked quite a bit with BibLaTeX in the past and, e.g., spent some time fine tuning the bibliography of my thesis for example, but BibLaTeX doesn't play well with the arxiv, so I would rather both recommend using it.

My wishlist would be: full title and author list (maybe switch too et al. After something like 10 authors), doi, eprint and url links. Preferably no issue but volume and year. Support for as many non-standard entry types (beyond @article and @book) as possible. Unfortunately I don't know BibTeX well enough to put something along those lines together with reasonable effort. Maye we can ask around in the community? Or look at a few past papers that had a particularly nice bibliography how authors did that?

Awesome would be if we could automatically do some input validation, e.g., check that the eprint filed has the right format that the doi filed starts with "10." and that url starts with http.

**Comment by harrow** [comment]
A bibstyle I recently used is
https://github.com/harrow/arxiv-bibstyle/blob/master/plainnat-eprint.bst
It supports doi and eprint fields.
I don't have strong opinions that this is the best way to go but it's one valid option.

**Comment by johannesjmeyer** [comment]
@cgogolin I would say we ship this now and treat the bibstyle as a separate project, David Wierichs was interested to help! If you agree I would merge this branch

**Comment by cgogolin** [comment]
Agree. Shall we also bump the version number and make new release?

**Comment by johannesjmeyer** [comment]
Let's do this after I changed the rsmf reference, too.

**Pull request merged**
