### PR TITLE
Minor fixes for quantum bibliographystyle

### PR DESCRIPTION
**Pull request by dwierichs**
Implements suggested and required changes in #126

### CODE REVIEW

**Comment by dwierichs** [comment]
One of the problems for the CI check seems to be `\textsuperscript` or `\textsubscript` in the `quantumview-template`, but according to [this page](https://www.ctan.org/pkg/subscript) these commands should be native LaTex by now... @cgogolin ,do you have an idea what could be the problem there?
There also is a second issue with the citations in the `quantumview-template` check but for this I am a bit clueless as well. I can't reproduce either issue locally as I don't have a minimalistic latex installation available.

**Comment by cgogolin** [comment]
I was also very surprised by the subscript issue and found this page https://tex.stackexchange.com/questions/248794/textsubscript-not-working-anymore-after-update, which points in the same direction. Probably this is an issue with the latex version used on our Travis runner and not a problem with our latex code. I will look ine this more in the coming days.



On December 8, 2021 1:07:40 AM GMT+01:00, David Wierichs ***@***.***> wrote:
>One of the problems for the CI check seems to be `\textsuperscript` or `\textsubscript` in the `quantumview-template`, but according to [this page](https://www.ctan.org/pkg/subscript) these commands should be native LaTex by now... @cgogolin ,do you have an idea what could be the problem there?
>There also is a second issue with the citations in the `quantumview-template` check but for this I am a bit clueless as well. I can't reproduce either issue locally as I don't have a minimalistic latex installation available.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/quantum-journal/quantum-journal/pull/127#issuecomment-988361093
-- 
Christian Gogolin
http://www.cgogolin.de

**Comment by dwierichs** [comment]
From the log file of Travis:
Screenshot from 2021-12-09 10-21-22

So indeed, this is a problem with Travis using a LaTeX version that is older than 10 years :D
subscript and superscript appear to be included in the core from 2015/01/01 onwards.

**Comment by dwierichs** [comment]
Hey @cgogolin I got it to work, using the `fixltx2e` package that contained `\textsubscript` and `\textsuperscript` before they were included in the LaTeX core (Locally, this package will be loaded but not needed, that should not cause issues). Also, there was a tiny change to be made to the `.travis.yml` to make it work with the `multibib` approach in `quantum-bibliographystyle-demo`: Loading `texlive-bibtex-extra` to load the package and applying the `bibtex` command to the sub-bibliography files instead of the main file.

The `nolink` functionality and warning modification are included as well :)

I can't request a review, but this would be ready for review.

Comments:
- `quantum_bst_with_shorturl.bst` was an old version of `quantum.bst`, which now also contains `shorturl`. The former has been removed.
- Some deletions, like the `bsts` working directory being ignored in `.gitignore` and the `\iffalse` block in the demo have been removed.
- As you suggested, all occurrences of `quantum_bst_demo` are replaced by `quantum-bibliographystyle-demo`

**Comment by cgogolin** [comment]
Amazing, thank you so much! This now looks all great! I will merge.

**Pull request merged**
