### PR TITLE
Prepare submission to CTAN

### PR DESCRIPTION
**Pull request by johannesjmeyer**
Hi quanta,

I just had to push a small change so that all relevant files are included in the CTAN submission. It now consists of the following: 

image

### CODE REVIEW

**Comment by dwierichs** [comment]
I don't know the syntax for the `.ps1` file, but can ask stupid questions :)
Is it correct that the files 
- `example_plot.py`
- `install.sh`
- `quantumarticle.layout`
are not included? :) I suppose for the first one, users may download it from GitHub here rather than obtaining it via CTAN? For the others I'm lacking insight in what they provide to the full package and whether they might be needed or not, sorry.

**Review by dwierichs — COMMENTED** [review]
I don't know the syntax for the .ps1 file, but can ask stupid questions :)
Is it correct that the files
- `example_plot.py`
- `install.sh`
- `quantumarticle.layout`

are not included? :) I suppose for the first one, users may download it from GitHub here rather than obtaining it via CTAN? For the others I'm lacking insight in what they provide to the full package and whether they might be needed or not, sorry.

**Comment by johannesjmeyer** [comment]
I was thinking that CTAN serves for people to access the latex files and use this to typeset their documents, so I think in principle only the `.cls` files are mandatory, but I also included the sources to make the docs.

And what file is `quantumarticle.layout`?

**Comment by dwierichs** [comment]
I don't know what the `.layout` file does... Probably it's fine then! :)

**Comment by johannesjmeyer** [comment]
I think this was related to either lyx or pandoc, I don't think it makes sense to distribute this via CTAN

**Comment by cgogolin** [comment]
Agree. Only the latex package and documentation plus examples should got to CTAN.

Do we need to specify a license somewhere? Because we have the problem that this repo is no longer purely LaTeX project licensed because the bib style is MIT. 

On March 24, 2022 3:34:04 PM GMT+01:00, Johannes Jakob Meyer ***@***.***> wrote:
>I think this was related to either lyx or pandoc, I don't think it makes sense to distribute this via CTAN
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/quantum-journal/quantum-journal/pull/137#issuecomment-1077695172
>You are receiving this because your review was requested.
>
>Message ID: ***@***.***>
-- 
Christian Gogolin
http://www.cgogolin.de

**Comment by johannesjmeyer** [comment]
License is specified in a separate form, I'll see that I put in the proper license! 

If the files are fine with you so far, please make an accepting review.

**Review by cgogolin — APPROVED** [review]

**Comment by johannesjmeyer** [comment]
Sorry, @cgogolin, it also appears that you have to merge it in.

**Comment by johannesjmeyer** [comment]
Nevermind, I realize that I still have to update the readme

**Comment by johannesjmeyer** [comment]
Sorry for the last comment, I think the readme is fine

**Comment by johannesjmeyer** [comment]
CTAN upload is done

**Comment by cgogolin** [comment]
Strange that the CI/CD pipeline is hanging. I will investigate, but not today...

**Pull request merged**
