### PR TITLE
WIP: Travis CI integration

### PR DESCRIPTION
**Pull request by cgranade**
This PR addresses #19 by enabling Travis CI integration and automatically building LaTeX templates. Currently, this is broken due to issues travis-ci/apt-package-whitelist#3484 and travis-ci/apt-package-whitelist#3483. Once complete, Travis CI support must be manually turned on at https://travis-ci.org/profile before merging the PR.

### CODE REVIEW

**Comment by cgogolin** [comment]
Green light from my side. This can be merged as soon as the white list requests in Travis have been resolved.

**Comment by cgranade** [comment]
It looks like one of the two Travis CI whitelist requests was approved, while something went wrong with font support. I'll investigate in more detail soon.

**Comment by cgogolin** [comment]
@cgranade can you possibly check the status of the Travis whitelist requests?

**Comment by cgranade** [comment]
It looks like the `texlive-xcolor` apt-get package is still not whitelisted, so the build is still failing. I could use a `sudo`-based build to mitigate the problem, but that precludes using container-based builds and may lead to problems later. Thoughts?

**Comment by cgogolin** [comment]
I would rather have a solution that will work long term and wait for that a bit longer. It will be less work in the end :)

**Comment by cgranade** [comment]
That makes sense. I'll keep watching for the Travis whitelist, then.

**Comment by cgranade** [comment]
The one unit test we have now passes. I'd like to start adding smaller test documents later, each testing a different set of conditions, but getting the template itself tested is a big step in the right direction, I think. @cgogolin, would you be willing to flip the switch on Travis CI to check PRs? Thanks!

**Comment by cgogolin** [comment]
Thanks for all the work! This is great and will save us a lot of headaches later!

I have activated travis via [ https://travis-ci.org/profile](https://travis-ci.org/profile). After the last step I ended up on a page that says:

> One more thing
> 
> Just a few more seconds as we talk to GitHub to find out which repositories belong to you.
> 
> If you're part of an organization that already has repositories set up on Travis CI, we'll take you to the list once we're done.
> 
> If you're not part of any existing organizations yet, we'll take you to a handy getting started guide to get you off the ground quickly.

and then nothing happened. Travis however seems to have found my repositories (they are displayed in my profile) and I have switched it on for quantum-journal.

**Comment by cgogolin** [comment]
Travis has recognized the .travis.yml, automatically stated a build, and it is running now.

**Comment by cgranade** [comment]
💕

**Pull request merged**
