### PR TITLE
Quantum bst code quality

### PR DESCRIPTION
**Pull request by dwierichs**
Here I collect some improvements to be made to quantum.bst, many of which are not of high importance or impact.
This also includes cleaning up and commenting the code for future development help.

(Copy of #131 for technical reasons)

### CODE REVIEW

**Comment by cgogolin** [comment]
Thanks for taking the time for this cleanup work! Could you have a look into why the tests tail? Thanks!

**Comment by dwierichs** [comment]
Done :) I'll try to add a documentation for every single function. This will increase the file size, but hopefully it will make editing and adding features much easier. I personally found it quite a hard switch from modern languages to this stack-based reverse-notation language.
If you prefer to go ahead with the release already now, that would be alright I guess, and the improved documented version would just be here in the repository?

**Comment by dwierichs** [comment]
@cgogolin I included comments for all functions that do not immediately produce a bib entry. Mostly, they explain which input and output arguments they have, in order to allow for debugging and understanding the code structure.
Some longer functions also have an explanation of their logic structure.

**Comment by cgogolin** [comment]
Looks great now!

**Pull request merged**
