### PR TITLE
WIP: Layout and example for LyX

### PR DESCRIPTION
**Pull request by cgranade**
This PR represents work in progress towards addressing #10, and provides a very basic layout that can be used with LyX to develop `{quantumarticle}` documents. The layout is currently missing a wide range of different features, but can be used to at least generate a basic document.

I've placed the new folder in a `layouts` folder in anticipation of creating layouts for other engines, such as Pandoc.

(**NB**: the LyX example file currently uses the new layout in "local layout" mode, and thus does not refer to LyX's internal store of layout files to find `{quantumarticle}`; this should be fixed before shipping the example.)

### CODE REVIEW

**Comment by cgogolin** [comment]
Is there a way to keep the content of lexample.lyx in line with the content of quantum-template.tex? The latter contains some non-trivial information about how to typeset articles, in particular the part on DOIs.

**Comment by cgranade** [comment]
I can manually copy over content from the existing plain-LaTeX template, to be sure. I had not yet done so for this work in progress, as the LyX layout is currently missing support for some of the features used by `quantum-template.tex`. My plan was to copy over more content as I develop the LyX layout, such that the LyX rendering is nearly identical to the rendering from LaTeX alone.

**Comment by cgranade** [comment]
Some remaining issues exposed by f3d2b16:
- [ ] No blank line is added between `\end{abstract}` and the start of the main body.
- [ ] `\openone` is not rendered correctly within LyX, though it does still output correctly in the PDF.
- [ ] Link colors are not set correctly by the LyX layout.

**Comment by cgogolin** [comment]
Ok, great! It is sad that the content has to be copied manually, but I think it will be important to keep the two in line. I think that we will not be changing the template often, so this is fine.

**Comment by cgogolin** [comment]
Just to keep you up to date on changes in quantum-template.tex: the way \hyperref is recommended to be included has changed and in the end of the first paragraph after the abstract a sentence has been added describing the new "click the title" feature of the class.

**Comment by cgogolin** [comment]
Closing because we now have a LyX layout.

**Pull request closed without merging**
