### PR TITLE
LyX layout + template

### PR DESCRIPTION
**Pull request by valbert4**
LyX layout file and template file added. Template file not named "quantum-template.lyx" because LyX exports this file to the TeX file "quantum-template.tex", which is in conflict with the TeX template.

### CODE REVIEW

**Comment by cgogolin** [comment]
Looks good. My only concern is the `nopdfoutputerror` option. That should really not be set by default. We need to find a way to make LyX put `\pdfoutput=1` into the preamble of the `.tex` file. I don't know how this can be done. But doesn't LyX have a way to put custom LaTeX code into the preamble, such as `\usepackage` commands?

**Comment by ComradeVVA** [comment]
The usual used defined preamble comes way later than the first five lines.
There are options I could tweak so that different packages or their options
are declared in the LyX defined preamble (which includes the first five
lines), but nothing to the extent of defining variables. Is pdfoutput a
variable that can be passed to a package? Is there anything else I should
know about it?


Best,
Victor

**Comment by ComradeVVA** [comment]
Update: I can get `\pdfoutput=1` to go on the second line after `documentclass`. LyX has `\usepackage[utf8]{inputenc}` going on the first line. Disabling that line and having it go after `\makeatletter` leads to various inputenc errors for some reason. At this point, I satisfy what arXiv wants but still require the `nopdfoutputerror` flag. I am wondering if this is sufficient for your purposes.

**Comment by valbert4** [comment]
Ok, now `\pdfoutput=1` is on the first line of the resulting TeX file (which I've also now included). Inputenc error was fixed by writing an accent as `\'{i}`. This file works with arXiv's TeXLive and my own MiKTeX setups, and no more `nopdfoutputerror ` option.

**Comment by cgogolin** [comment]
That's awesome! I will look into it in more detail in the coming days.

**Comment by cgogolin** [comment]
Looks good! @cgranade, what do you think? Can we maybe add a sentence in a prominent location that this is a beta feature and that the text of the template generated through this lyx file might not always be perfectly in sync with the tex template? That would be my last request before we can merge this.

**Comment by valbert4** [comment]
Thanks. I put in a comment in both files.

**Comment by cgogolin** [comment]
Thanks! Merged!

**Pull request merged**
